name: first 

on: push

jobs:
  job1:
    name: first Job
    runs-on: ubuntu-latest 
    steps:
      - name: steps
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort
  job2:
    name: Second Job
    runs-on: windows-latest
    steps: 
      - name: Step One
        uses: actions/checkout
      - name: Step two
        run: " Get-ChildItem Env: | Sort-Object Name "  
